replicaCount: 1

image:
  tag: "stable2"

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - host: mis.demo.mirix.io
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: mis.demo.mirix.io
      hosts:
        - mis.demo.mirix.io

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi